#!/usr/bin/env python3

from haishoku.haishoku import Haishoku
import os
import sys

def rgb_to_hex(rgb):
    return '#%02x%02x%02x' % rgb

def main(argv):
    path=os.path.expanduser('~/.config/wall')
    hex=rgb_to_hex(Haishoku.getPalette(path)[1][1])
    print(hex)

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))

