#!/bin/bash
set -euo pipefail -o noclobber # Bash sanity checking

# The usage string
print_usage () {
cat << EOF
usage: set_colours [options] <colour>    set colours to given value
   or: set_colours [options] -           read colour from stdin
EOF
}

if [ $# -eq 0 ]; then
	print_usage
	exit 1
fi

RELOAD=false

while [[ $# -gt 1 ]]
do
	case "$1" in
		-r|--reload)
			RELOAD=true
			shift
		;;
	esac
done

case $1 in
	-)
		colour=$(tee)
		shift
	;;
	*)
		colour=$1
	;;
esac;

dotfiles="$HOME/repos/config"

polybar_config="${dotfiles}/polybar/config"
rofi_theme="${dotfiles}/rofi/styles/full.css"
i3_config="${dotfiles}/i3/config.d/colours.sh"
vis_theme="${dotfiles}/vis/colors/accent"

sed -i --follow-symlinks "/accent = /c\	accent = ${colour}" $polybar_config
sed -i --follow-symlinks "/accent: /caccent: ${colour};" $rofi_theme
sed -i --follow-symlinks "/accent=/caccent=\'${colour}\'" $i3_config
echo ${colour} >| $vis_theme

if [ $RELOAD ]; then
	"${dotfiles}/i3/restart"
fi
