#!/bin/bash
set -euo pipefail -o noclobber # Bash sanity checking

# The usage string
print_usage () {
cat << EOF
usage: set-colour <colour>    set colours to given value
   or: set-colour -           read colour from stdin
EOF
}

if [ $# -eq 0 ]; then
	print_usage
	exit 1
fi

RELOAD=false

case $1 in
	-)
		colour=$(tee)
	;;
	-r|--reload)
		RELOAD=true
	;;
	*)
		colour=$1
	;;
esac;

dotfiles="$HOME/repos/config"
polybar_config="${dotfiles}/polybar/config"
rofi_theme="${dotfiles}/rofi/rofi_full.css"
i3_config="${dotfiles}/i3/config"

sed -i --follow-symlinks "/accent = /c\	accent = ${colour}" $polybar_config
sed -i --follow-symlinks "/accent: /caccent: ${colour};" $rofi_theme
sed -i --follow-symlinks "/set \$accent /cset \$accent \"${colour}\"" $i3_config

if [ $RELOAD ]; then
	i3-msg restart
fi
