#!/bin/bash
set -euo pipefail -o noclobber # Bash sanity checking

# The usage string
print_usage () {
cat << EOF
usage: set_colours [options] <colour>    set colours to given value
   or: set_colours [options] -           read colour from stdin
EOF
}

if [ $# -eq 0 ]; then
	print_usage
	exit 1
fi

RELOAD=false

while [[ $# -gt 1 ]]
do
	case "$1" in
		-r|--reload)
			RELOAD=true
			shift
		;;
	esac
done

case $1 in
	-)
		colour=$(tee)
		shift
	;;
	*)
		colour=$1
	;;
esac;

# Get the directory ../
dotfiles="$(dirname "$(dirname "$(realpath $0)"))")"

# Create the output directory if it does not exist
mkdir -p "${dotfiles}/colours/out"

user_settings="${dotfiles}/settings/user.conf"
[[ ! -e $user_settings ]] && touch $user_settings

vis_theme="${dotfiles}/vis/colors/accent"
mkdir -p "${dotfiles}/vis/colors"
[[ ! -e $vis_theme ]] && touch $vis_theme

main="${dotfiles}/colours/out/theme"

sed -i --follow-symlinks "/accent = /c\	accent = ${colour}" $user_settings
echo ${colour} | tee $vis_theme $main

if [ $RELOAD ]; then
	[[ $(pgrep vis) ]] && pkill -USR1 vis
	"${dotfiles}/i3/restart"
fi
