let mapleader=" "

" Syntax highlighting
syntax on

" Don't try to be compatible with vi
set nocompatible

" Whitespace
set tabstop=4
set shiftwidth=4
set autoindent
set noexpandtab
set breakindent

" Searching
set incsearch " Search incrementally
set hlsearch  " Search highlights all of the results

" Rendering
set ttyfast
set background=dark
set mouse=a

" Numbering system
set number
set relativenumber

function ToggleRelativeNumbers()
	if (&relativenumber == 1)
		set norelativenumber
	else
		set relativenumber
	endif
endfunction

" Map gl to toggle numbering between absolute and relative
nnoremap gl :call ToggleRelativeNumbers()<CR>

" tex shortcuts
function MathAbbrev()
	iabbrev mms \begin{align*}<CR><CR>\end{align*}<++><Esc>==kS
	iabbrev mma \begin{align} <CR><CR>\end{align} <++><Esc>==kS
endfunction

" Call the above functions to set up default commands for individual filetypes
au FileType tex :call MathAbbrev()

" Enable spelling by default for certain filetypes
au FileType tex, markdown :Spell
set spelllang=en_gb
