#!/bin/bash

monitor1=HDMI-1
monitor2=eDP-1
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

killall -q conky polybar dunst redshift
pkill -f dropdown_calculator
pkill -f dropdown_terminal

# CONKY
# while pgrep -x conky >/dev/null; do sleep 1; done
# conky &

# REDSHIFT
redshift &

# POLYBAR
while pgrep -x polybar >/dev/null; do sleep 1; done
MONITOR=$monitor1 polybar top &
MONITOR=$monitor2 polybar top &

# CALCULATOR
while pgrep -f dropdown_calculator >/dev/null; do sleep 1; done
"$DIR/dropdown/calculator" &

# TERMINAL
while pgrep -f dropdown_terminal >/dev/null; do sleep 1; done
"$DIR/dropdown/terminal" &
