#!/bin/sh -eu

# Adapted from https://github.com/xmonad/xmonad-testing/blob/master/build-scripts/build-with-stack.sh

SRC_DIR=~/.xmonad
EXE_NAME=xmonad-x86_64-linux

# Unset STACK_YAML, to ensure that $SRC_DIR/stack.yaml is used.
unset STACK_YAML

# Do the build.
cd $SRC_DIR
stack build

# Create a hard link at the requested destination, replacing any existing one.
ln -f -T "$(stack exec -- which $EXE_NAME)" "$1"
