#!/bin/bash

alias c='clear'
alias cat='bat --style=grid,numbers'
alias cl='claude'
alias cls='clear'
alias claer='clear'
alias cbi='xsel -ib' # Clipboard in (copy) using xsel
alias cbo='xsel -ob' # Clipboard out (paste) using xsel
alias ccat='highlight --out-format=xterm256' # Coloured cat w/ syntax highlighting
alias cmatrix='cmatrix -bC red' # Nerdy matrix
alias d='dune'
alias db='dune build'
alias dc='dune build @check'
alias dr='dune runtest --force'
alias dcr='docker-compose restart'
alias g='git'
alias gr='GR_ROOT="$(git-root)" && cd "$GR_ROOT" && unset GR_ROOT'
alias k='kubectl'
alias r='ranger'
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias ls='ls --color=auto -1' # --group-directories-first --color=auto'
alias lsa='ls --color=auto -1' # --group-directories-first --color=auto -labh'
alias t='tfc'
alias p='sudo pacman'
alias prf='pr-format'
alias ship='s ship'
alias sv='sudo nvim'
alias wad='cd ~/src/github.com/monzo/wearedev'
alias wthr='curl -4 http://wttr.in/'
alias v='nvim'
alias vim='nvim'
alias w='worktree switch wearedev -c'

alias sp='dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause >> /dev/null'
alias snext='dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next >> /dev/null'
alias sprev='dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous >> /dev/null'
alias splay='dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play >> /dev/null'
alias spause='dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause >> /dev/null'


