#!/usr/bin/env bash
# 
#  diff -- show a diff between the user's environment and the declarative specification

set -euo pipefail

USER_NIX="/home/craigfe/t/dotfiles/nix/user.nix"
USER_NIX_QUERY=$(nix-env -qaf $USER_NIX)

{ diff --color=always --unified=0 \
  --label current <(nix-env -q) \
  --label "$(basename $USER_NIX)" <(echo "$USER_NIX_QUERY") || true; } \
  | { grep -v '@@' || true; }
