#!/bin/bash
pass=$(gpg --decrypt --quiet ~/.credentials/password_email.gpg)

# Escape special characters in password
pass=$(printf '%q' "$pass")

echo "set smtp_pass=\"$pass\""
echo "set imap_pass=\"$pass\""
