#!/bin/bash

DOTFILES="$(dirname "$(dirname "$(dirname "$(realpath $0)"))")")"
THEME_INPUT="$HOME/.config/rofi/styles/pass.css"

# Generate the theme file using a named pipe
THEME_OUTPUT="$HOME/.config/rofi/styles/.pipe-theme"
[ ! -p $THEME_OUTPUT ] && mkfifo "$HOME/.config/rofi/styles/.pipe-theme"
$DOTFILES/settings/settings stream "$THEME_INPUT" "$THEME_OUTPUT" &

rofi -dmenu -password -p "" -theme "$THEME_OUTPUT" -i
