#!/bin/bash

DOTFILES="$(dirname "$(dirname "$(dirname "$(realpath $0)"))")")"
THEME_INPUT="$HOME/.config/rofi/styles/sidebar.css"

# Generate the theme file using a named pipe
THEME_OUTPUT="$HOME/.config/rofi/styles/.pipe-theme"
[ ! -p $THEME_OUTPUT ] && mkfifo "$HOME/.config/rofi/styles/.pipe-theme"
$DOTFILES/settings/settings stream "$THEME_INPUT" "$THEME_OUTPUT" &

rofi -show drun -theme "$THEME_OUTPUT" -display-drun "RUN: "

# Flush the pipe
dd if=$THEME_OUTPUT iflag=nonblock of=/dev/null
