#!/bin/bash

DOTFILES="$(dirname "$(dirname "$(dirname "$(realpath $0)"))")")"
THEME_INPUT="$HOME/.config/rofi/styles/full.css"

# Generate the theme file using a named pipe
THEME_OUTPUT="$HOME/.config/rofi/styles/.pipe-theme"
[ ! -p $THEME_OUTPUT ] && mkfifo "$HOME/.config/rofi/styles/.pipe-theme"
$DOTFILES/settings/settings stream "$THEME_INPUT" "$THEME_OUTPUT" &

action=$(echo -e "RELOAD\nCOLOUR\nBLUETOOTH\nLOCK\nSUSPEND\nLOGOUT\nREBOOT\nPOWEROFF" | \
	awk '{print $(NF-1)}' | \
	rofi -theme "$THEME_OUTPUT" -dmenu -i -p "SYSTEM: ")

# Flush the pipe
dd if=$THEME_OUTPUT iflag=nonblock of=/dev/null

case $action in

	RELOAD)
		xrdb -load ~/.Xdefaults
		i3-msg reload
		i3-msg restart
	;;

	BLUETOOTH)
		exec ~/.scripts/bt_connect
	;;

	COLOUR)
		exec ~/.config/rofi/menu/colour
	;;

	LOCK)
		exec lock
	;;

	SUSPEND)
		exec systemctl suspend
	;;

	LOGOUT)
		prompt_rofi LOGOUT "i3-msg exit"
	;;

	REBOOT)
		prompt_rofi REBOOT "reboot"
	;;

	POWEROFF)
		prompt_rofi POWEROFF "poweroff"
	;;

	*)
		echo $action
	;;

esac
