#!/bin/bash

action=$(echo -e "RELOAD\nCOLOUR\nLOCK\nSUSPEND\nLOGOUT\nREBOOT\nPOWEROFF" | \
	awk '{print $(NF-1)}' | \
	rofi -theme "$HOME/.config/rofi/styles/full.css" -dmenu -i -p "SYSTEM: ")

case $action in

	RELOAD)
		xrdb -load ~/.Xdefaults
		i3-msg reload
		i3-msg restart
	;;

	COLOUR)
		exec ~/.config/rofi/menu/colour
	;;

	LOCK)
		exec lock
	;;

	SUSPEND)
		exec systemctl suspend
	;;

	LOGOUT)
		prompt_rofi LOGOUT "i3-msg exit"
	;;

	REBOOT)
		prompt_rofi REBOOT "reboot"
	;;

	POWEROFF)
		prompt_rofi POWEROFF "poweroff"
	;;

	*)
		echo $action
	;;

esac

