#!/bin/bash

ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full.css -m 0 -fullscreen)

action=$(echo -e "RELOAD\nCOLOUR\nLOCK\nLOGOUT\nREBOOT\nPOWEROFF" | \
	awk '{print $(NF-1)}' | \
	rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")

case $action in

	RELOAD)
		xrdb -load ~/.Xdefaults
		i3-msg reload
		i3-msg restart
	;;

	COLOUR)
		exec ~/.config/rofi/menu/colour
	;;

	LOCK)
		exec lock
	;;

	LOGOUT)
		prompt_rofi LOGOUT "i3-msg exit"
	;;

	REBOOT)
		prompt_rofi REBOOT "reboot"
	;;

	POWEROFF)
		prompt_rofi POWEROFF "poweroff"
	;;

	*)
		echo $action
	;;

esac

