#!/bin/bash
# A dmenu confirm prompt script
# Gives a dmenu prompt labelled with $1 to perform command $1
# For example: './prompt "Do you want to shutdown?" "shutdown -h now"

[ $(echo -e "No\nYes" | dmenu -i -p "$1") == "Yes" ] && $2
