#!/bin/bash

if [ -z $1 ]; then
	>&2 echo "No filepath supplied"
	exit 1
fi

if [ -f ~/.config/wall.png ]; then
	feh --bg-scale ~/.config/wall.png

elif [ -f ~/.config/wall.jpg ]; then
	feh --bg-scale ~/.config/wall.jpg

fi
