#!/usr/bin/env python3

import os
import shutil
import subprocess
import sys

def eprint(*args, **kwargs):
    """Print a series of strings to stderr."""
    print(*args, file=sys.stderr, **kwargs)

def main(argv):
    if len(argv) != 2:
        eprint("Usage: set_wallpaper <file>")
        return 1

    fullpath = os.path.abspath(argv[1])
    filepath, ext = os.path.splitext(fullpath)

    if not os.path.isfile(fullpath):
        eprint("Argument must be a file")
        return 2

    if not (ext == ".jpg" or ext == ".png"):
        eprint("The supplied file must have a recognised extension (.jpg, .png)")
        return 3

    dest = os.path.expanduser("~/.config/wall")
    shutil.copy(fullpath,dest)

    rc = subprocess.call(['feh', '--no-fehbg', '--bg-scale', dest])
    return 0 if rc == 0 else 4

if __name__ == "__main__":
    sys.exit(main(sys.argv))

