#!/bin/bash
set -euo pipefail

command -v patdiff >/dev/null 2>&1 || { echo >&2 "Error: missing dependency 'patdiff'"; exit 1; }

if [ $# -lt 2 ]; then
    echo >&2 "Usage: diff-ast [options] <prev> <next>"
    exit 1
fi

ARGS="${*: 1:$#-2}"
PREV="${*: -2:1}"
NEXT="${*: -1:1}"

patdiff <(ocamlfind ppx_tools/dumpast "$ARGS" "$PREV") \
	<(ocamlfind ppx_tools/dumpast "$ARGS" "$NEXT")
