#!/usr/bin/env python3

import argparse
import os
import shutil
import subprocess
import sys

def parse_arguments(argv):
    parser = argparse.ArgumentParser(prog=argv[0], description="Set the desktop wallpaper.")
    parser.add_argument("path", help='path to the image to use')
    parser.add_argument("--theme", action="store_true", help="reload the theme using the colour palette")
    return parser.parse_args(sys.argv[1:])

def eprint(*args, **kwargs):
    """Print a series of strings to stderr."""
    print(*args, file=sys.stderr, **kwargs)

def main(argv):
    args = parse_arguments(argv)
    fullpath = os.path.abspath(args.path)
    filepath, ext = os.path.splitext(fullpath)

    if not os.path.isfile(fullpath):
        eprint("Argument must be a file")
        return 2

    if not (ext == ".jpg" or ext == ".png"):
        eprint("The supplied file must have a recognised extension (.jpg, .png)")
        return 3

    dest = fullpath
    rc = subprocess.call(['feh', '--bg-fill', dest])

    if rc != 0:
        return 4

    resolution = subprocess.check_output("xrandr | grep '\*' | cut -f4 -d ' ' | cut -f1 -d '+' | head -n 1",shell=True)
    print("Detected resolution: " + str(resolution) + "\n")

    resolution = "2560x1440"

    rc = subprocess.call(['betterlockscreen', '--update', dest, '--resolution', resolution, '--blur', '1'])

    if rc != 0:
        return 5

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))

