#!/usr/bin/python

import todoist
import sys

api = todoist.TodoistAPI('b00925d694e9b3c1618523a70c2df2add4c7e490')
api.sync()
full_name = api.state['user']['full_name']

api.items.add(sys.argv[1])
api.commit()


