#!/bin/bash
set -euxo pipefail

# Variant of the `tree` command that respects .gitignore files
IGNORED=$(git check-ignore ./* 2>/dev/null);

if [ -z "$IGNORED" ]; then
    /usr/bin/tree
else
    echo "$IGNORED" | awk '{print "-I " $0}' | xargs /usr/bin/tree --prune
fi
