#!/bin/bash
DOTFILES="$(dirname "$(dirname "$(realpath "$0")")")"

# re-generate the polybar config
mkdir -p "$HOME/.config/polybar/out"
"$DOTFILES/settings/settings" stream "$HOME/.config/polybar/config" "$HOME/.config/polybar/out/config"

for m in $(polybar --list-monitors | cut -d":" -f1); do
	MONITOR=$m polybar --reload top --config="$HOME/.config/polybar/out/config" &
done

