#!/bin/zsh

export ZSH="/usr/share/oh-my-zsh"
export ZSH_HOME="/usr/share/zsh"
export LANG=en_GB.UTF-8

ZSH_THEME="craigfe"

# Use Vi mode
bindkey -v

export PATH="$HOME/.local/bin:$HOME/.scripts:$PATH:$(ruby -e 'puts Gem.user_dir')/bin:$HOME/.yarn/bin"

COMPLETION_WAITING_DOTS="false"

# Don't mark untracked files as dirty
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git vi-mode ssh-agent)

source $ZSH/oh-my-zsh.sh
source $ZSH_HOME/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH_HOME/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.aliases
[ -f $HOME/.shortcuts/out/shell ] && source $HOME/.shortcuts/out/shell

# User configuration

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
  # export EDITOR="emacsclient --alternate-editor='emacs' --no-wait --create-frame"
fi

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

PROMPT_EOL_MARK=" •"

# Python virtual environment configuration
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/repos
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_SCRIPT=$HOME/.local/bin/virtualenvwrapper.sh
# source $HOME/.local/bin/virtualenvwrapper_lazy.sh

# Use the Vi navigation keys in menu completion
zstyle ':completion:*' menu select
zmodload zsh/complist

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

bindkey '^[[[SE' autosuggest-execute

bindkey -s '^g' 'projectgoto\n'

# Jump (https://github.com/gsamokovarov/jump)
eval "$(jump shell)"

# OPAM configuration
. /home/craigfe/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# AWS credentials
# . ~/.aws/get_credentials.sh

# Travis configuration
# [ -f /home/craigfe/.travis/travis.sh ] && source /home/craigfe/.travis/travis.sh

fh() {
    print -z $(history |\
                   fzf --no-sort --tac |\
                   sed -E 's/ *[0-9]*\*? *//; s/\\/\\\\/g')
}

ch() {
    local cols sep google_history open
    cols=$(( COLUMNS / 3 ))
    sep='{::}'

    if [ "$(uname)" = "Darwin" ]; then
        google_history="$HOME/Library/Application Support/Google/Chrome/Default/History"
        open=open
    else
        google_history="$HOME/.config/google-chrome/Default/History"
        open=xdg-open
    fi
    cp -f "$google_history" /tmp/h
    sqlite3 -separator $sep /tmp/h \
            "select substr(title, 1, $cols), url
     from urls order by last_visit_time desc" |
        awk -F $sep '{printf "%-'$cols's  \x1b[36m%s\x1b[m\n", $1, $2}' |
        fzf --ansi --multi | sed 's#.*\(https*://\)#\1#' | xargs $open > /dev/null 2> /dev/null
}

# Nix configuration
export NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs/archive/release-19.09.tar.gz"
export PATH="$PATH:$HOME/.nix-profile/bin"
export NIX_REMOTE=daemon

# Set up Node Version Manager
export NVM_DIR="$HOME/.nvm"                            # You can change this if you want.
export NVM_SOURCE="/usr/share/nvm"                     # The AUR package installs it to here.
[ -s "$NVM_SOURCE/nvm.sh" ] && . "$NVM_SOURCE/nvm.sh"  # Load NVM

# Oskel configuration
export PATH="$PATH:$HOME/t/oskel/_build/install/default/bin"
export OSKEL_FULL_NAME="Craig Ferguson"
export OSKEL_EMAIL="me@craigfe.io"
export OSKEL_GITHUB_ORG="CraigFe"
export OSKEL_OCAMLFORMAT_OPTIONS="parse-docstrings=true,break-infix=fit-or-vertical,module-item-spacing=compact"

export PATH="$PATH:$HOME/t/dune-release/_build/install/default/bin"

