export ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="craigfe"

bindkey -v # Use Vi mode

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="false"

# Don't mark untracked files as dirty
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
	git
	vi-mode
	ssh-agent
	zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.aliases
[ -f $HOME/.shortcuts/out/shell ] && source $HOME/.shortcuts/out/shell

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR="emacsclient --alternate-editor='emacs' --no-wait --create-frame"
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

PROMPT_EOL_MARK=" •"

# Python virtual environment configuration
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/repos
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_SCRIPT=$HOME/.local/bin/virtualenvwrapper.sh
source $HOME/.local/bin/virtualenvwrapper_lazy.sh

# Use the Vi navigation keys in menu completion
zstyle ':completion:*' menu select
zmodload zsh/complist

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

bindkey '^[[[SE' autosuggest-execute

# OPAM configuration
. /home/craigfe/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# Travis configuration
[ -f /home/craigfe/.travis/travis.sh ] && source /home/craigfe/.travis/travis.sh
