# Make default directory the windows root
export WINDOWS="/mnt/c/Users/Craig/"
cd $WINDOWS

# Set environment variables
export PS1='\[\033[1;31m\][\[\033[1;36m\]\u\[\033[1;31m\]@\[\033[1;32m\]\h \[\033[1;31m\]: \[\033[1;35m\]\W\[\033[1;31m\]]$ \[\033[0m\]' 
export EDITOR='vim'
