#!/bin/bash

[[ -f ~/.bashrc ]] && . ~/.bashrc


export PATH="$PATH:$HOME/.scripts:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/go/src/github.com/xintron/xmonad-log:$HOME/.vim/bundle/vim-live-latex-preview/bin"
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="chromium-browser --enable-plugins --force-device-scale-factor=1.25"
export BROWSER_PRIVATE="chromium-browser --enable-plugins --force-device-scale-factor=1.25 --incognito"
export MUSIC="spotify --force-device-scale-factor=1.1"
export SUDO_ASKPASS=~/repos/dotfiles/rofi/menu/password
export MONITOR_1="eDP-1"
export MONITOR_2="HDMI-1"

